import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `wasm-pack build ./wasm --target web` and gitignored.
    "wasm/pkg/**",
  ]),
  {
    rules: {
      // Every intra-repo import goes through the `@/` alias; see AGENTS.md.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["./*", "./**", "../*", "../**"],
              message: "Use the @/ alias instead of a relative path.",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
